### ISSUE TITLE
heightGetter need to calculate the height of each item?

### ISSUE THREAD

**Issue by ansonhcz** [fengbujue2022/react-native-waterfall#9]
heightGetter 函数是不是给我列的宽度和index，确保我可以找到对应的item，但是该item的高度需要自己计算

**Comment by fengbujue2022** [comment]
是的

**Comment by fengbujue2022** [comment]
[react-native-virtualized-masonry](https://github.com/iftechio/react-native-virtualized-masonry)
或许你可以参考下这个repo 它是用FlatList实现的
